export const ELEMENTS = {
    codigocupom:'.cupom-codigo',
    validacaocodigocupom:'be.visible',
    resultadocupom:'#cupomResultado > .titulo',
    validacaoresultadocupom:'be.visible',
    valortotal:'.total > .titulo',
    validacaovalortotal:'be.visible',
    checkendereco:'input[name="endereco_principal"]',
    validacaocheckendereco:'be.checked',
    checkformaenvio:'#formaEnvio1-sedex',
    validacaocheckformaenvio:'be.checked',
    selecaocartaodecredito:'#radio-cartao',
    validacaoimagemcartao:'.jp-card-front',
    numerocartao:'#cartao_cartao_numero',
    datavencimentocarta:'#cartao_cartao_data_expiracao',
    titularcartao:'#cartao_cartao_nome',
    cvvcartao:'#cartao_cartao_cvv',
    check1:'#cartao_check_dados_titular',
    validacaocheck1:'be.empty',
    check2:'#cartao_check_dados_fatura',
    validacaocheck2:'be.empty',
    seletordeparcelas:'#cartao_cartao_parcelas',
    validacaovalorfinal:'#escolha-cartao',
    btnfinalizarcompra:'#finalizarCompra',
    validacaobtnfinalizarcompra:'be.visible',
    mensagemSucesso:'//*[@id="corpo"]/div/div[1]/div/div[1]/div[1]/ul[1]/li[1]/h4',
}

