export const ELEMENTS = {
    idconfirmacaoemail: '#id_confirmacao_email',
    validacaoemail: 'be.visible',
    senha: '#id_senha',
    confirmacaosenha:'#id_confirmacao_senha',
    checkpf: '#id_tipo_0',
    nome: '#id_nome',
    validacaonome:'be.visible',
    cpf: '#id_cpf',
    validacaocpf: 'be.visible',
    celular: '#id_telefone_celular',
    validacaocelular: 'be.visible',
    telefone:'#id_telefone_principal',
    validacaotelefone:'be.visible',
    sexo: '#id_sexo',
    validacaosexo:'be.visible',
    datadenascimento:'#id_data_nascimento',
    validacaodatadenascimento:'be.visible',
    cep:'#id_cep',
    validacaocep: 'be.visible',
    endereco:'#id_endereco',
    validacaoendereco: 'be.visible',
    numeroresidencial:'#id_numero',
    validacaonumeroresidencial:'be.visible',
    complemento: '#id_complemento',
    validacaocomplemento: 'be.visible',
    referencia: '#id_referencia',
    validacaoreferencia: 'be.visible',
    bairro: '#id_bairro',
    validacaobairro:'be.visible',
    cidade:'#id_cidade',
    validacaocidade:'be.visible',
    estado:'#id_estado',
    validacaoestado:'be.visible',
}