
export const ELEMENTS = {
    clicarPrimeiroProduto:':nth-child(2) > .row-fluid > :nth-child(1) > .listagem-item > .produto-sobrepor',
    btncomprar:'div.principal > .acoes-produto > .comprar > .botao',
    validacaopaginacomprar: 'be.visible',
    paginacarrinho:'.span12 > .titulo',
    validacaopaginacarrinho:'be.visible',
    btncontinuarcomprando:'.span12 > a.botao',
    validacaobtncontinuarcomprando:'be.visible',
    qaStore: '.logo > a',
    clicarSegundoProduto:':nth-child(4) > .row-fluid > :nth-child(3) > .listagem-item > .produto-sobrepor',
    validacaoqaStore:'be.visible',
    calcularfrete: '#calcularFrete',
    validacaocalcularfrete: 'be.visible',
    campocupom:'#usarCupom',
    clicarlixeira:'[data-produto-id="118475039"] > :nth-child(6) > .excluir > .icon-trash',
    removidosucesso:'.alert-success',
    validacaoremovidosucesso:'be.visible',
    checkterceiraopcao:'[type="radio"]',
    btnusarcupom:':nth-child(4) > [colspan="4"] > .form-horizontal > .control-group > .controls > .input-append > .btn',
    validacaobtnusarcupom:'be.visible',
    descontoaplicado:'#cupom_desconto',
    validacaodescontoaplicado:'be.visible',
    valortotal:'.total > .titulo',
    validacaovalortotal:'be.visible',
    btnapagarcupom:'.text-error',
    campocupomvazio:'be.empty',
    cupomfretegratisaplicado:'.cupom-valor > .cor-secundaria',
    validacaocupomfretegratisaplicado:'be.visible',
    btnfinalizarcompra:'.span12 > .principal',
    mensagemCupomNaoEncontrado: '//*[@id="corpo"]/div/div[1]/text()',
    mensagemCupomInexistente: '//*[@id="corpo"]/div/div[1]/text()',
}